baseURL: https://geordiekidd.com/
languageCode: en-gb
title: geordiekidd.com
summaryLength: 10

copyright: (c) Geordie Kidd

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      typographer: false

pluralizelisttitles: false

params:
  slogan: "Geordie's permanent online residence."
